[package]
name = "yubi-rust-tool"
version = "0.1.0"
edition = "2024"
readme = "README.md"

[dependencies]
yubikey-hmac-otp = "0.10"

[[bin]]
name = "ykchalresp"
path = "src/main.rs"

[[bin]]
name = "xtask"
path = "src/xtask.rs"
